platform :ios, '7.0'

target 'VTDirectDemo' do
    project 'VTDirectDemo.xcodeproj'
    pod 'MidtransKit'
    pod 'SDWebImage', '~>3.7'
    pod 'SRMonthPicker'
    pod 'JVFloatLabeledTextField'
    pod 'IQKeyboardManager'
    pod 'ActionSheetPicker-3.0'
    pod 'iOS-Color-Picker'
    pod 'MBProgressHUD'
end
