//
//  VTPaymentResult.h
//  MidtransCoreKit
//
//  Created by Akbar Taufiq Herlangga on 3/15/16.
//  Copyright © 2016 Veritrans. All rights reserved.
//

#import <Foundation/Foundation.h>

/**
 Object that represent the payment result.
 */
@interface VTPaymentResult : NSObject

/**
 The HTTP status code received from server.
 */
@property(nonatomic, readonly) NSInteger statusCode;

/**
 The server's message about this transaction.
 */
@property(nonatomic, readonly) NSString *statusMessage;

/**
 The transaction ID generated by server.
 */
@property(nonatomic, readonly) NSString *transactionId;

/**
 The resulting transaction status.
 */
@property(nonatomic, readonly) NSString *transactionStatus;

/**
 The order ID for this transaction. This value is generated client-side.
 */
@property(nonatomic, readonly) NSString *orderId;

/**
 The type of the payment.
 */
@property(nonatomic, readonly) NSString *paymentType;

/**
 Data holder object that contains various payment-specific data.
 */
@property(nonatomic, readonly) NSDictionary *additionalData;

///---------------------
/// @name Initialization
///---------------------

/**
 TODO: This should only be used internally.
 */
- (instancetype)initWithStatusCode:(NSInteger)statusCode
                     statusMessage:(NSString *)statusMessage
                     transactionId:(NSString *)transactionId
                 transactionStatus:(NSString *)transactionStatus
                           orderId:(NSString *)orderId
                       paymentType:(NSString *)paymentType
                    additionalData:(NSDictionary *)additionalData;

@end
