# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MidtransCoreKit' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!
  pod 'Clickstream', :git => 'https://github.com/gojek/clickstream-ios.git', :branch => 'support-objc'
  pod 'Clickstream/EventVisualizer', :git => 'https://github.com/gojek/clickstream-ios.git', :branch => 'support-objc'
  # Pods for MidtransCoreKit

  target 'MidtransCoreKitTests' do
    # Pods for testing
  end

end

target 'MidtransCoreKitStatic' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MidtransCoreKitStatic

end

post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
    end
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
        end
    end
end
