# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MidtransCoreKit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'ClickstreamLib', :git => 'https://github.com/gojek/clickstream-ios.git', :tag => '2.0.21'
  # Pods for MidtransCoreKit

  target 'MidtransCoreKitTests' do
    # Pods for testing
  end

end

target 'MidtransCoreKitStatic' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MidtransCoreKitStatic

end
