# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MidtransDemo' do
    # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
    use_frameworks!
    
    # Pods for MidtransDemo
    pod 'CHRTextFieldFormatter'
    pod 'JGProgressHUD'
    pod 'ACFloatingTextfield-Objc'
    pod 'IQKeyboardManager'
    pod 'BKMoneyKit', '~> 0.0'
    
    pod 'MidtransKit', :path => '../'
    pod 'MidtransCoreKit', :path => '../'
#    
#    target 'MidtransDemoUITests' do
#        inherit! :search_paths
#        # Pods for testing
#    end
    
end

post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
    end
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
        end
    end
end

