# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MidtransDemo' do
    # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
    # use_frameworks!
    
    # Pods for MidtransDemo
    pod 'CHRTextFieldFormatter'
    pod 'JGProgressHUD'
    pod 'ACFloatingTextfield-Objc'
    pod 'IQKeyboardManager'
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'BKMoneyKit', '~> 0.0'
    
#    pod 'MidtransKit', :path => '../'
#    pod 'MidtransCoreKit', :path => '../'
#    
#    target 'MidtransDemoUITests' do
#        inherit! :search_paths
#        # Pods for testing
#    end
    
end
