// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: midtrans/clickstream/products/common/GopayTokenization.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

///platform="ios,android"

import Foundation
import SwiftProtobuf

public class Midtrans_Clickstream_Products_Common_GopayTokenization {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  ///MappedTo: "gopaytokenizationenabled"
  public var gopayTokenizationEnabled: Bool = false

  public var gopayTokenizationLinked: Bool = false

  public var gopayBalance: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  required public init() {}
}

#if swift(>=5.5) && canImport(_Concurrency)
extension Midtrans_Clickstream_Products_Common_GopayTokenization: @unchecked Sendable {}
#endif  // swift(>=5.5) && canImport(_Concurrency)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "midtrans.clickstream.products.common"

extension Midtrans_Clickstream_Products_Common_GopayTokenization: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GopayTokenization"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "gopay_tokenization_enabled"),
    2: .standard(proto: "gopay_tokenization_linked"),
    3: .standard(proto: "gopay_balance"),
  ]

  public func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.gopayTokenizationEnabled) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.gopayTokenizationLinked) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.gopayBalance) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.gopayTokenizationEnabled != false {
      try visitor.visitSingularBoolField(value: self.gopayTokenizationEnabled, fieldNumber: 1)
    }
    if self.gopayTokenizationLinked != false {
      try visitor.visitSingularBoolField(value: self.gopayTokenizationLinked, fieldNumber: 2)
    }
    if !self.gopayBalance.isEmpty {
      try visitor.visitSingularStringField(value: self.gopayBalance, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }
}

public extension Midtrans_Clickstream_Products_Common_GopayTokenization {
         
    @objc public convenience init(properties: [String:Any],
         eventName: String) {

         self.init()
         
        if let gopayTokenizationEnabled: Bool = properties["gopaytokenizationenabled"] as? Bool {
            self.gopayTokenizationEnabled = gopayTokenizationEnabled
        }
    }
}
