// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: midtrans/clickstream/meta/Merchant.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

///platform="ios,android"

import Foundation

/// Merchant information.
public class Midtrans_Clickstream_Meta_Merchant {
  //  Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var merchantID: String = String()

  public var merchantName: String = String()

  public var merchantURL: String = String()

  public var brand: String = String()

  public var businessType: String = String()

  public var entity: String = String()

  public var products: String = String()

  public var merchantType: String = String()

  public var unknownFields =  UnknownStorage()

  required public init() {}
}

#if swift(>=5.5) && canImport(_Concurrency)
extension Midtrans_Clickstream_Meta_Merchant: @unchecked Sendable {}
#endif  // swift(>=5.5) && canImport(_Concurrency)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "midtrans.clickstream.meta"

extension Midtrans_Clickstream_Meta_Merchant:  Message,  _MessageImplementationBase,  _ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Merchant"
  public static let _protobuf_nameMap:  _NameMap = [
    1: .standard(proto: "merchant_id"),
    2: .standard(proto: "merchant_name"),
    3: .standard(proto: "merchant_url"),
    4: .same(proto: "brand"),
    5: .standard(proto: "business_type"),
    6: .same(proto: "entity"),
    7: .same(proto: "products"),
    8: .standard(proto: "merchant_type"),
  ]

  public func decodeMessage<D:  Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.merchantID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.merchantName) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.merchantURL) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.brand) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.businessType) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.entity) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self.products) }()
      case 8: try { try decoder.decodeSingularStringField(value: &self.merchantType) }()
      default: break
      }
    }
  }

  public func traverse<V:  Visitor>(visitor: inout V) throws {
    if !self.merchantID.isEmpty {
      try visitor.visitSingularStringField(value: self.merchantID, fieldNumber: 1)
    }
    if !self.merchantName.isEmpty {
      try visitor.visitSingularStringField(value: self.merchantName, fieldNumber: 2)
    }
    if !self.merchantURL.isEmpty {
      try visitor.visitSingularStringField(value: self.merchantURL, fieldNumber: 3)
    }
    if !self.brand.isEmpty {
      try visitor.visitSingularStringField(value: self.brand, fieldNumber: 4)
    }
    if !self.businessType.isEmpty {
      try visitor.visitSingularStringField(value: self.businessType, fieldNumber: 5)
    }
    if !self.entity.isEmpty {
      try visitor.visitSingularStringField(value: self.entity, fieldNumber: 6)
    }
    if !self.products.isEmpty {
      try visitor.visitSingularStringField(value: self.products, fieldNumber: 7)
    }
    if !self.merchantType.isEmpty {
      try visitor.visitSingularStringField(value: self.merchantType, fieldNumber: 8)
    }
    try unknownFields.traverse(visitor: &visitor)
  }
}

public extension Midtrans_Clickstream_Meta_Merchant {
         
    @objc public convenience init(properties: [String:Any],
         eventName: String) {

         self.init()
         
    }
}
