// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: midtrans/clickstream/products/common/Product.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

///platform="ios,android"

import Foundation

public enum Midtrans_Clickstream_Products_Common_Product:  Enum {
  public typealias RawValue = Int
  case unspecified // = 0
  case snapSdk // = 1
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .snapSdk
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .snapSdk: return 1
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Midtrans_Clickstream_Products_Common_Product] = [
    .unspecified,
    .snapSdk,
  ]

}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension Midtrans_Clickstream_Products_Common_Product:  _ProtoNameProviding {
  public static let _protobuf_nameMap: _NameMap = [
    0: .same(proto: "PRODUCT_UNSPECIFIED"),
    1: .same(proto: "PRODUCT_SNAP_SDK"),
  ]
}

public extension Midtrans_Clickstream_Products_Common_Product {
         
    init(properties: [String:Any],
         eventName: String) {
         self.init()
         
        switch eventName {
        
            default:
                self = .unspecified

        }
    }
}
