# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MidtransSDK' do

  # Pods for MidtransSDK
  pod 'MidtransCoreKit', :path => '/Users/nanang/Workspace/Midtrans/Veritrans-ios-sdk [OLD]/'

end
